/*
 * Personnel Data
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AttendanceCreateRequestAttendancesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AttendanceCreateRequest
 */
public class AttendanceCreateRequestTest {
    private final AttendanceCreateRequest model = new AttendanceCreateRequest();

    /**
     * Model tests for AttendanceCreateRequest
     */
    @Test
    public void testAttendanceCreateRequest() {
        // TODO: test AttendanceCreateRequest
    }

    /**
     * Test the property 'attendances'
     */
    @Test
    public void attendancesTest() {
        // TODO: test attendances
    }

    /**
     * Test the property 'skipApproval'
     */
    @Test
    public void skipApprovalTest() {
        // TODO: test skipApproval
    }

}
