/*
 * Personnel Data
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CompensationAttribute
 */
public class CompensationAttributeTest {
    private final CompensationAttribute model = new CompensationAttribute();

    /**
     * Model tests for CompensationAttribute
     */
    @Test
    public void testCompensationAttribute() {
        // TODO: test CompensationAttribute
    }

    /**
     * Test the property 'attributeId'
     */
    @Test
    public void attributeIdTest() {
        // TODO: test attributeId
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'currencySymbol'
     */
    @Test
    public void currencySymbolTest() {
        // TODO: test currencySymbol
    }

    /**
     * Test the property 'overtimeHours'
     */
    @Test
    public void overtimeHoursTest() {
        // TODO: test overtimeHours
    }

    /**
     * Test the property 'bonusType'
     */
    @Test
    public void bonusTypeTest() {
        // TODO: test bonusType
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

}
