/*
 * Personnel Data
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateAbsencePeriodRequest
 */
public class CreateAbsencePeriodRequestTest {
    private final CreateAbsencePeriodRequest model = new CreateAbsencePeriodRequest();

    /**
     * Model tests for CreateAbsencePeriodRequest
     */
    @Test
    public void testCreateAbsencePeriodRequest() {
        // TODO: test CreateAbsencePeriodRequest
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'timeOffTypeId'
     */
    @Test
    public void timeOffTypeIdTest() {
        // TODO: test timeOffTypeId
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'halfDayStart'
     */
    @Test
    public void halfDayStartTest() {
        // TODO: test halfDayStart
    }

    /**
     * Test the property 'halfDayEnd'
     */
    @Test
    public void halfDayEndTest() {
        // TODO: test halfDayEnd
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'skipApproval'
     */
    @Test
    public void skipApprovalTest() {
        // TODO: test skipApproval
    }

}
