/*
 * Personnel Data
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AbsencePeriodBreakdown;
import com.konfigthis.client.model.AbsenceType;
import com.konfigthis.client.model.HourlyAbsencePeriodResponseAttributesCertificate;
import com.konfigthis.client.model.ShortEmployee;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for HourlyAbsencePeriodResponseAttributes
 */
public class HourlyAbsencePeriodResponseAttributesTest {
    private final HourlyAbsencePeriodResponseAttributes model = new HourlyAbsencePeriodResponseAttributes();

    /**
     * Model tests for HourlyAbsencePeriodResponseAttributes
     */
    @Test
    public void testHourlyAbsencePeriodResponseAttributes() {
        // TODO: test HourlyAbsencePeriodResponseAttributes
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'measurementUnit'
     */
    @Test
    public void measurementUnitTest() {
        // TODO: test measurementUnit
    }

    /**
     * Test the property 'effectiveDuration'
     */
    @Test
    public void effectiveDurationTest() {
        // TODO: test effectiveDuration
    }

    /**
     * Test the property 'employee'
     */
    @Test
    public void employeeTest() {
        // TODO: test employee
    }

    /**
     * Test the property 'absenceTypeId'
     */
    @Test
    public void absenceTypeIdTest() {
        // TODO: test absenceTypeId
    }

    /**
     * Test the property 'certificate'
     */
    @Test
    public void certificateTest() {
        // TODO: test certificate
    }

    /**
     * Test the property 'start'
     */
    @Test
    public void startTest() {
        // TODO: test start
    }

    /**
     * Test the property 'end'
     */
    @Test
    public void endTest() {
        // TODO: test end
    }

    /**
     * Test the property 'halfDayStart'
     */
    @Test
    public void halfDayStartTest() {
        // TODO: test halfDayStart
    }

    /**
     * Test the property 'halfDayEnd'
     */
    @Test
    public void halfDayEndTest() {
        // TODO: test halfDayEnd
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'origin'
     */
    @Test
    public void originTest() {
        // TODO: test origin
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'approvedAt'
     */
    @Test
    public void approvedAtTest() {
        // TODO: test approvedAt
    }

    /**
     * Test the property 'breakdowns'
     */
    @Test
    public void breakdownsTest() {
        // TODO: test breakdowns
    }

}
