/*
 * Personnel Data
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.HourlyAbsence;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for HourlyAbsencePeriodsResponseAllOfData
 */
public class HourlyAbsencePeriodsResponseAllOfDataTest {
    private final HourlyAbsencePeriodsResponseAllOfData model = new HourlyAbsencePeriodsResponseAllOfData();

    /**
     * Model tests for HourlyAbsencePeriodsResponseAllOfData
     */
    @Test
    public void testHourlyAbsencePeriodsResponseAllOfData() {
        // TODO: test HourlyAbsencePeriodsResponseAllOfData
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

}
